version: "3.0"

services:
  database:
    restart: 'unless-stopped'
    image: mysql
    container_name: labBases
    ports:
      - 3306:3306
    env_file:
      - db.env
    volumes:
      - ./parcial1:/parcial1

  mongo:
    restart: 'unless-stopped'
    image: mongo
    container_name: labBasesMongo
    volumes:
      - ./sharedvolume:/sharedvolume
    ports:
      - 127.0.0.1:27017:27017
