version: "3.0"

services:
  database:
    restart: 'unless-stopped'
    image: mysql
    container_name: labBases
    ports:
      - 3306:3306
    env_file:
      - db.env
  sakila:
    restart: 'unless-stopped'
    image: emicba/sakila
    container_name: sakilaLabBases
    ports:
      - 3307:3306
    env_file:
      - db.env
